import { useEffect, useState } from 'react'
import { ChevronDown, ChevronUp, ShieldCheck, X, BookOpen, CheckCircle2, AlertTriangle, ShoppingCart, Zap } from 'lucide-react'
import { listings } from '../data/listings.js'
import { fetchUserListings } from '../lib/api.js'

const CONDITION_ORDER = ['Like New', 'Very Good', 'Good', 'Acceptable']

const CONDITION_COLOR = {
  'Like New':   { color: '#067D62', bg: '#e6f4ea' },
  'Very Good':  { color: '#007185', bg: '#e0f0f3' },
  'Good':       { color: '#c45500', bg: '#fff3e0' },
  'Acceptable': { color: '#B12704', bg: '#fde8d8' },
}

function conditionCounts(items) {
  const counts = {}
  for (const item of items) {
    counts[item.conditionGrade] = (counts[item.conditionGrade] ?? 0) + 1
  }
  return counts
}

function ProductImage({ product }) {
  const fallback = `https://picsum.photos/seed/${product.id}/400/400`
  const [src, setSrc] = useState(product.image ?? fallback)
  const cfg = CONDITION_COLOR[product.conditionGrade] ?? CONDITION_COLOR['Good']
  return (
    <div className="w-full sm:w-[180px] flex-shrink-0">
      <div
        className="h-[170px] rounded-md border overflow-hidden relative"
        style={{ borderColor: '#D5D9D9' }}
      >
        <img
          src={src}
          alt={product.title}
          onError={() => setSrc(fallback)}
          className="w-full h-full object-cover"
        />
        <span
          className="absolute top-2 left-2 text-[10px] font-bold uppercase tracking-wide px-2 py-0.5 rounded-full"
          style={{ backgroundColor: cfg.bg, color: cfg.color }}
        >
          {product.tag}
        </span>
      </div>
    </div>
  )
}

function ConditionReport({ item, onClose }) {
  const cfg = CONDITION_COLOR[item.conditionGrade] ?? CONDITION_COLOR['Good']
  return (
    <div
      className="mt-4 rounded-md border p-5 bg-[#FBFBFB]"
      style={{ borderColor: '#D5D9D9' }}
    >
      <div className="flex items-start justify-between gap-4 mb-4">
        <div className="flex items-center gap-3 flex-wrap">
          <span
            className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-sm font-bold"
            style={{ backgroundColor: cfg.bg, color: cfg.color }}
          >
            <ShieldCheck size={13} />
            {item.conditionGrade}
          </span>
          <span className="text-sm text-[#565959]">
            {item.conditionReport.confidence}% confidence
          </span>
          <span className="text-sm text-[#565959]">
            Score: {item.conditionScore}/100
          </span>
        </div>
        <button
          type="button"
          onClick={onClose}
          className="flex-shrink-0 p-1 rounded hover:bg-[#E3E6E6] transition-colors"
          aria-label="Close report"
        >
          <X size={16} style={{ color: '#565959' }} />
        </button>
      </div>

      <div className="flex flex-wrap gap-2 mb-4">
        {item.conditionReport.observations.map((obs) => (
          <span
            key={obs}
            className="text-xs px-2.5 py-1 rounded-full border"
            style={{ borderColor: '#D5D9D9', color: '#555', backgroundColor: 'white' }}
          >
            {obs}
          </span>
        ))}
      </div>

      <div className="rounded-md border bg-white p-4" style={{ borderColor: '#D5D9D9' }}>
        <p className="text-xs font-bold uppercase tracking-[0.18em] text-[#879596] mb-1">
          Encore condition summary
        </p>
        <p className="text-sm text-[#565959] leading-relaxed">
          {item.conditionReport.summary}
        </p>
      </div>

      <p className="text-xs text-[#879596] mt-3">
        AI-generated by Amazon Encore. Verified before listing.
      </p>
    </div>
  )
}

export default function Marketplace({ searchQuery = '', onAddToCart, onBuyNow }) {
  const [activeGrade, setActiveGrade] = useState(null)
  const [openReportId, setOpenReportId] = useState(null)
  const [userItems, setUserItems] = useState([])
  const [addedId, setAddedId] = useState(null)

  function handleAddToCart(product) {
    setAddedId(product.id)
    if (onAddToCart) onAddToCart(product)
    setTimeout(() => setAddedId(null), 1800)
  }

  function handleBuyNow(product) {
    if (onBuyNow) onBuyNow(product)
  }

  /* fetch user-listed items from Supabase on mount and every 5s */
  useEffect(() => {
    async function load() {
      try {
        const { listings: items } = await fetchUserListings()
        if (items?.length) {
          const mapped = items.map(item => ({
            id: item.id,
            title: item.title,
            category: item.category || 'General',
            conditionScore: item.condition_score || 80,
            conditionGrade: item.condition_grade || 'Good',
            price: Number(item.price) || 0,
            originalPrice: Number(item.original_price) || 0,
            image: item.image_url || null,
            tag: 'Just listed',
            rating: '—',
            reviews: 'New',
            delivery: 'FREE delivery by Amazon',
            conditionReport: {
              confidence: item.condition_score || 80,
              observations: item.observations || [],
              summary: item.condition_summary || item.description || '',
            },
            userListed: true,
          }))
          setUserItems(mapped)
        }
      } catch { /* silent fail */ }
    }
    load()
    const interval = setInterval(load, 5000)
    return () => clearInterval(interval)
  }, [])

  const allListings = [...userItems, ...listings]

  const q = searchQuery.trim().toLowerCase()
  const searchFiltered = q
    ? allListings.filter(l =>
        l.title.toLowerCase().includes(q) ||
        l.category.toLowerCase().includes(q) ||
        l.conditionGrade.toLowerCase().includes(q) ||
        (l.conditionReport?.summary || '').toLowerCase().includes(q)
      )
    : allListings

  const counts = conditionCounts(searchFiltered)
  const filtered = activeGrade
    ? searchFiltered.filter((l) => l.conditionGrade === activeGrade)
    : searchFiltered

  function toggleReport(id) {
    setOpenReportId((prev) => (prev === id ? null : id))
  }

  return (
    <section id="marketplace" className="px-4 pb-10">
      <div className="max-w-[1500px] mx-auto">
        <div className="rounded-md border bg-white overflow-hidden" style={{ borderColor: '#D5D9D9' }}>
          <div className="grid xl:grid-cols-[250px_minmax(0,1fr)]">
            {/* Sidebar */}
            <aside
              className="border-b xl:border-b-0 xl:border-r bg-[#FBFBFB] p-5"
              style={{ borderColor: '#D5D9D9' }}
            >
              <h2 className="text-2xl font-bold mb-2" style={{ color: '#0F1111' }}>
                Encore marketplace
              </h2>
              <p className="text-sm text-[#565959] mb-5">
                AI-verified listings that look and shop like familiar Amazon results.
              </p>

              <div className="space-y-5 text-sm">
                <div>
                  <p className="font-bold text-[#0F1111] mb-2">Encore Verified</p>
                  <label className="flex items-center gap-2 text-[#565959] cursor-pointer">
                    <span
                      className="h-4 w-4 rounded-sm border flex items-center justify-center"
                      style={{ borderColor: '#D5D9D9', backgroundColor: '#067D62' }}
                    >
                      <ShieldCheck size={10} color="white" />
                    </span>
                    Show verified items only
                  </label>
                </div>

                <div>
                  <div className="flex items-center justify-between mb-2">
                    <p className="font-bold text-[#0F1111]">Condition</p>
                    {activeGrade && (
                      <button
                        type="button"
                        className="text-xs font-semibold"
                        style={{ color: '#007185' }}
                        onClick={() => setActiveGrade(null)}
                      >
                        Clear
                      </button>
                    )}
                  </div>
                  {CONDITION_ORDER.map((grade) => {
                    const count = counts[grade] ?? 0
                    if (!count) return null
                    const active = activeGrade === grade
                    return (
                      <button
                        key={grade}
                        type="button"
                        onClick={() => setActiveGrade(active ? null : grade)}
                        className="w-full flex items-center justify-between text-left mb-1 px-2 py-1 rounded transition-colors"
                        style={{
                          backgroundColor: active ? '#fff8e0' : 'transparent',
                          color: active ? '#c45500' : '#565959',
                        }}
                      >
                        <span className={active ? 'font-semibold' : ''}>{grade}</span>
                        <span className="text-xs">{count}</span>
                      </button>
                    )
                  })}
                </div>

                <div>
                  <p className="font-bold text-[#0F1111] mb-2">Second-life route</p>
                  {['Resell', 'Refurbished', 'Open-box'].map((item) => (
                    <div key={item} className="text-[#565959] mb-1 px-2">{item}</div>
                  ))}
                </div>
              </div>
            </aside>

            {/* Listings */}
            <div className="p-5 md:p-6">
              <div className="flex flex-col md:flex-row md:items-end md:justify-between gap-3 mb-6">
                <div>
                  <p className="text-sm text-[#565959]">
                    1–{filtered.length} of {filtered.length} result{filtered.length !== 1 ? 's' : ''}
                    {q ? ` for "${searchQuery}"` : activeGrade ? ` for "${activeGrade}"` : ' for Encore picks'}
                  </p>
                  <h3 className="text-2xl font-bold text-[#0F1111]">
                    {q ? `Results for "${searchQuery}"` : activeGrade ? `${activeGrade} condition` : 'Popular second-life listings'}
                  </h3>
                </div>
                <p className="text-sm font-semibold" style={{ color: '#007185' }}>
                  Prices reflect condition, not wishful thinking
                </p>
              </div>

              {/* Second-life books featured section — hidden when searching non-book term */}
              {(() => {
                const bookListings = listings.filter((l) => l.category === 'Books')
                if (!bookListings.length) return null
                if (q && !q.includes('book')) return null

                function extractAttr(observations, keywords) {
                  const obs = observations.find((o) =>
                    keywords.some((k) => o.toLowerCase().includes(k))
                  )
                  if (!obs) return null
                  const negatives = ['tear', 'crack', 'damage', 'worn', 'bend', 'bent', 'dog-ear', 'pen ']
                  const isNeg = negatives.some((n) => obs.toLowerCase().includes(n))
                  return { text: obs, positive: !isNeg }
                }

                return (
                  <div
                    className="rounded-md border p-5 mb-6"
                    style={{ borderColor: '#D5D9D9', backgroundColor: '#f0faf5' }}
                  >
                    <div className="flex items-center gap-2.5 mb-1">
                      <BookOpen size={20} style={{ color: '#067D62' }} />
                      <h4 className="text-lg font-bold" style={{ color: '#0F1111' }}>
                        Second-life books
                      </h4>
                    </div>
                    <p className="text-sm text-[#565959] mb-4">
                      Where it all started. Amazon began selling books — Encore brings them back.
                    </p>

                    <div className="overflow-x-auto">
                      <div className="flex gap-4">
                        {bookListings.map((book) => {
                          const cfg = CONDITION_COLOR[book.conditionGrade] ?? CONDITION_COLOR['Good']
                          const fallback = `https://picsum.photos/seed/${book.id}/400/400`
                          const spine = extractAttr(book.conditionReport.observations, ['spine'])
                          const annotations = extractAttr(book.conditionReport.observations, ['annotation', 'highlight', 'pencil', 'note', 'pen'])
                          const pages = extractAttr(book.conditionReport.observations, ['page', 'intact'])

                          return (
                            <div
                              key={book.id}
                              className="min-w-[280px] max-w-[300px] rounded-md border bg-white p-4 flex flex-col gap-3 flex-shrink-0"
                              style={{ borderColor: '#D5D9D9' }}
                            >
                              <div className="h-[140px] rounded-md overflow-hidden border" style={{ borderColor: '#D5D9D9' }}>
                                <img
                                  src={book.image ?? fallback}
                                  alt={book.title}
                                  onError={(e) => { e.target.src = fallback }}
                                  className="w-full h-full object-cover"
                                />
                              </div>

                              <a
                                href="#marketplace"
                                className="text-sm font-medium leading-snug hover:underline line-clamp-2"
                                style={{ color: '#007185' }}
                              >
                                {book.title}
                              </a>

                              <div className="flex items-center gap-2">
                                <span
                                  className="inline-flex rounded-full px-2.5 py-0.5 text-[10px] font-bold uppercase tracking-wide"
                                  style={{ backgroundColor: cfg.bg, color: cfg.color }}
                                >
                                  {book.conditionGrade}
                                </span>
                                <span className="text-xs text-[#565959]">Score: {book.conditionScore}/100</span>
                              </div>

                              <div className="flex items-baseline gap-2">
                                <span className="text-xl font-medium" style={{ color: '#0F1111' }}>
                                  ₹{book.price.toLocaleString('en-IN')}
                                </span>
                                <span className="text-sm text-[#565959] line-through">
                                  ₹{book.originalPrice.toLocaleString('en-IN')}
                                </span>
                              </div>

                              <div className="border-t pt-3" style={{ borderColor: '#D5D9D9' }}>
                                <p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#879596] mb-2">
                                  Book condition
                                </p>
                                <div className="space-y-1.5">
                                  {spine && (
                                    <div className="flex items-center gap-1.5 text-xs">
                                      {spine.positive
                                        ? <CheckCircle2 size={13} style={{ color: '#067D62' }} />
                                        : <AlertTriangle size={13} style={{ color: '#c45500' }} />}
                                      <span className="text-[#565959]"><span className="font-semibold text-[#0F1111]">Spine:</span> {spine.text}</span>
                                    </div>
                                  )}
                                  {annotations && (
                                    <div className="flex items-center gap-1.5 text-xs">
                                      {annotations.positive
                                        ? <CheckCircle2 size={13} style={{ color: '#067D62' }} />
                                        : <AlertTriangle size={13} style={{ color: '#c45500' }} />}
                                      <span className="text-[#565959]"><span className="font-semibold text-[#0F1111]">Annotations:</span> {annotations.text}</span>
                                    </div>
                                  )}
                                  {pages && (
                                    <div className="flex items-center gap-1.5 text-xs">
                                      {pages.positive
                                        ? <CheckCircle2 size={13} style={{ color: '#067D62' }} />
                                        : <AlertTriangle size={13} style={{ color: '#c45500' }} />}
                                      <span className="text-[#565959]"><span className="font-semibold text-[#0F1111]">Pages:</span> {pages.text}</span>
                                    </div>
                                  )}
                                </div>
                              </div>
                            </div>
                          )
                        })}
                      </div>
                    </div>
                  </div>
                )
              })()}

              <div className="divide-y" style={{ borderColor: '#E7E7E7' }}>
                {filtered.map((product) => {
                  const cfg = CONDITION_COLOR[product.conditionGrade] ?? CONDITION_COLOR['Good']
                  const isOpen = openReportId === product.id
                  return (
                    <div key={product.id} className="py-5 first:pt-0 last:pb-0"
                      style={product.userListed ? { borderLeft: '3px solid #FF9900', paddingLeft: 16, backgroundColor: '#fffdf5' } : {}}>
                      <div className="flex flex-col md:flex-row gap-5">
                        <ProductImage product={product} />

                        <div className="min-w-0 flex-1">
                          <div className="flex items-center gap-2 mb-2 flex-wrap">
                            <ShieldCheck size={14} style={{ color: '#067D62' }} />
                            <span className="text-xs font-bold uppercase tracking-wide text-[#067D62]">
                              Encore Verified
                            </span>
                            {product.userListed && (
                              <span className="text-[10px] font-bold uppercase tracking-wider px-2.5 py-0.5 rounded-full"
                                style={{ backgroundColor: '#FF9900', color: '#fff' }}>
                                Just listed
                              </span>
                            )}
                            <span className="text-xs text-[#565959]">{product.category}</span>
                          </div>

                          <a
                            href="#marketplace"
                            className="block text-lg leading-snug font-medium hover:underline"
                            style={{ color: '#007185' }}
                          >
                            {product.title}
                          </a>

                          <div className="flex items-center gap-2 flex-wrap mt-1 text-sm">
                            <span className="text-[#C7511F]">★★★★☆</span>
                            <span style={{ color: '#007185' }}>{product.rating}</span>
                            <span style={{ color: '#007185' }}>({product.reviews})</span>
                            <span className="text-[#565959]">
                              Condition score: {product.conditionScore}/100
                            </span>
                          </div>

                          <div className="flex items-center gap-2 flex-wrap mt-2">
                            <span
                              className="inline-flex rounded-full px-3 py-1 text-xs font-bold"
                              style={{ backgroundColor: cfg.bg, color: cfg.color }}
                            >
                              {product.conditionGrade}
                            </span>
                            {product.conditionReport.summary ? (
                              <span className="text-sm text-[#565959]">
                                {product.conditionReport.summary.length > 80
                                  ? `${product.conditionReport.summary.slice(0, 80)}…`
                                  : product.conditionReport.summary}
                              </span>
                            ) : null}
                          </div>

                          <p className="text-sm mt-3" style={{ color: '#067D62' }}>
                            {product.delivery}
                          </p>
                          <p className="text-sm text-[#565959] mt-1">
                            30-day return window. Backed by Encore condition support.
                          </p>
                        </div>

                        <div className="md:w-[210px] flex-shrink-0">
                          <div
                            className="rounded-md border p-4 bg-[#FBFBFB]"
                            style={{ borderColor: '#D5D9D9' }}
                          >
                            <p className="text-[13px] text-[#565959] mb-1">Starting price</p>
                            {product.price > 0 ? (
                              <>
                                <div className="flex items-baseline gap-2 flex-wrap">
                                  <span className="text-3xl font-medium text-[#0F1111]">
                                    ₹{product.price.toLocaleString('en-IN')}
                                  </span>
                                  {product.originalPrice > 0 && (
                                    <span className="text-sm text-[#565959] line-through">
                                      ₹{product.originalPrice.toLocaleString('en-IN')}
                                    </span>
                                  )}
                                </div>
                                {product.originalPrice > 0 && product.price < product.originalPrice && (
                                  <p className="text-sm font-semibold mt-1" style={{ color: '#067D62' }}>
                                    {Math.round((1 - product.price / product.originalPrice) * 100)}% off original
                                  </p>
                                )}
                              </>
                            ) : (
                              <p className="text-base font-semibold mt-1 text-[#565959]">Price on request</p>
                            )}
                            {product.price > 0 && (
                              <button
                                type="button"
                                onClick={() => handleAddToCart(product)}
                                className="mt-4 w-full py-2.5 rounded-full font-semibold text-sm transition-all flex items-center justify-center gap-2"
                                style={{
                                  backgroundColor: addedId === product.id ? '#067D62' : '#FFD814',
                                  color: addedId === product.id ? 'white' : '#0F1111',
                                }}
                              >
                                <ShoppingCart size={14} />
                                {addedId === product.id ? 'Added to cart' : 'Add to cart'}
                              </button>
                            )}
                            {product.price > 0 && (
                              <button
                                type="button"
                                onClick={() => handleBuyNow(product)}
                                className="mt-2 w-full py-2.5 rounded-full font-semibold text-sm transition-all flex items-center justify-center gap-2"
                                style={{ backgroundColor: '#FF9900', color: 'white' }}
                              >
                                <Zap size={14} />
                                Buy now
                              </button>
                            )}
                            <button
                              type="button"
                              onClick={() => toggleReport(product.id)}
                              className="mt-2 w-full py-2 rounded-full border text-sm font-semibold flex items-center justify-center gap-1.5 transition-all"
                              style={{
                                borderColor: isOpen ? '#007185' : '#D5D9D9',
                                color: isOpen ? '#007185' : '#0F1111',
                                backgroundColor: isOpen ? '#e0f0f3' : '#F7F8F8',
                              }}
                            >
                              {isOpen ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
                              {isOpen ? 'Hide report' : 'See condition report'}
                            </button>
                          </div>
                        </div>
                      </div>

                      {isOpen && (
                        <ConditionReport item={product} onClose={() => setOpenReportId(null)} />
                      )}
                    </div>
                  )
                })}
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
