import { useEffect, useState } from 'react'
import { ChevronDown, ChevronUp, ShieldCheck, X, BookOpen, CheckCircle2, AlertTriangle, ShoppingCart, Zap, Package, MapPin } from 'lucide-react'
import { listings, DEMO_LOCATION } from '../data/listings.js'
import { fetchUserListings } from '../lib/api.js'
import { useAuth } from '../context/AuthContext.jsx'

const CONDITION_ORDER = ['Like New', 'Very Good', 'Good', 'Acceptable']

const CONDITION_COLOR = {
  'Like New':   { color: '#067D62', bg: '#e6f4ea' },
  'Very Good':  { color: '#007185', bg: '#e0f0f3' },
  'Good':       { color: '#c45500', bg: '#fff3e0' },
  'Acceptable': { color: '#B12704', bg: '#fde8d8' },
}

function conditionCounts(items) {
  const counts = {}
  for (const item of items) {
    counts[item.conditionGrade] = (counts[item.conditionGrade] ?? 0) + 1
  }
  return counts
}

function ProductImage({ product }) {
  const fallback = `https://picsum.photos/seed/${product.id}/400/400`
  const mainImg = product.image ?? fallback
  const extras = Array.isArray(product.additional_images) ? product.additional_images : []
  const allImgs = [mainImg, ...extras].filter(Boolean)
  const [activeIdx, setActiveIdx] = useState(0)
  const [src, setSrc] = useState(allImgs[0])
  const cfg = CONDITION_COLOR[product.conditionGrade] ?? CONDITION_COLOR['Good']

  function goTo(i) {
    setActiveIdx(i)
    setSrc(allImgs[i] ?? fallback)
  }

  return (
    <div className="w-full sm:w-[180px] flex-shrink-0">
      <div
        className="h-[170px] rounded-md border overflow-hidden relative"
        style={{ borderColor: '#D5D9D9' }}
      >
        <img
          src={src}
          alt={product.title}
          onError={() => setSrc(fallback)}
          className="w-full h-full object-cover"
        />
        <span
          className="absolute top-2 left-2 text-[10px] font-bold uppercase tracking-wide px-2 py-0.5 rounded-full"
          style={{ backgroundColor: cfg.bg, color: cfg.color }}
        >
          {product.tag}
        </span>
        {allImgs.length > 1 && (
          <span className="absolute bottom-1.5 right-2 text-[10px] font-bold px-1.5 py-0.5 rounded-full"
            style={{ backgroundColor: 'rgba(0,0,0,0.5)', color: '#fff' }}>
            {activeIdx + 1}/{allImgs.length}
          </span>
        )}
      </div>
      {allImgs.length > 1 && (
        <div className="flex gap-1 mt-1.5 overflow-x-auto">
          {allImgs.map((img, i) => (
            <button key={i} type="button" onClick={() => goTo(i)}
              className="w-9 h-9 rounded border flex-shrink-0 overflow-hidden transition-all"
              style={{ borderColor: activeIdx === i ? '#FF9900' : '#D5D9D9', borderWidth: activeIdx === i ? 2 : 1 }}>
              <img src={img} alt="" className="w-full h-full object-cover" onError={() => {}} />
            </button>
          ))}
        </div>
      )}
    </div>
  )
}

function ConditionReport({ item, onClose }) {
  const cfg = CONDITION_COLOR[item.conditionGrade] ?? CONDITION_COLOR['Good']
  return (
    <div
      className="mt-4 rounded-md border p-5 bg-[#FBFBFB]"
      style={{ borderColor: '#D5D9D9' }}
    >
      <div className="flex items-start justify-between gap-4 mb-4">
        <div className="flex items-center gap-3 flex-wrap">
          <span
            className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-sm font-bold"
            style={{ backgroundColor: cfg.bg, color: cfg.color }}
          >
            <ShieldCheck size={13} />
            {item.conditionGrade}
          </span>
          <span className="text-sm text-[#565959]">
            {item.conditionReport.confidence}% confidence
          </span>
          <span className="text-sm text-[#565959]">
            Score: {item.conditionScore}/100
          </span>
        </div>
        <button
          type="button"
          onClick={onClose}
          className="flex-shrink-0 p-1 rounded hover:bg-[#E3E6E6] transition-colors"
          aria-label="Close report"
        >
          <X size={16} style={{ color: '#565959' }} />
        </button>
      </div>

      <div className="flex flex-wrap gap-2 mb-4">
        {item.conditionReport.observations.map((obs) => (
          <span
            key={obs}
            className="text-xs px-2.5 py-1 rounded-full border"
            style={{ borderColor: '#D5D9D9', color: '#555', backgroundColor: 'white' }}
          >
            {obs}
          </span>
        ))}
      </div>

      <div className="rounded-md border bg-white p-4" style={{ borderColor: '#D5D9D9' }}>
        <p className="text-xs font-bold uppercase tracking-[0.18em] text-[#879596] mb-1">
          Encore condition summary
        </p>
        <p className="text-sm text-[#565959] leading-relaxed">
          {item.conditionReport.summary}
        </p>
      </div>

      <p className="text-xs text-[#879596] mt-3">
        AI-generated by Amazon Encore. Verified before listing.
      </p>
    </div>
  )
}

export default function Marketplace({ searchQuery = '', onAddToCart, onBuyNow, onProductClick, initialTab = 'all' }) {
  const { user } = useAuth() ?? {}
  const [activeTab, setActiveTab] = useState(initialTab) // 'all' | 'mine'
  const [activeGrade, setActiveGrade] = useState(null)
  const [activeCategory, setActiveCategory] = useState(null)
  const [savedCategory, setSavedCategory] = useState(null)
  const [openReportId, setOpenReportId] = useState(null)
  const [userItems, setUserItems] = useState([])
  const [addedId, setAddedId] = useState(null)

  // Reset to "all" tab when user logs out
  useEffect(() => { if (!user) setActiveTab('all') }, [user])

  function handleAddToCart(product) {
    setAddedId(product.id)
    if (onAddToCart) onAddToCart(product)
    setTimeout(() => setAddedId(null), 1800)
  }

  function handleBuyNow(product) {
    if (onBuyNow) onBuyNow(product)
  }

  /* restore last-browsed category from localStorage */
  useEffect(() => {
    const saved = localStorage.getItem('encore_last_category')
    if (saved) setSavedCategory(saved)
  }, [])

  /* fetch user-listed items from Supabase on mount and every 5s */
  useEffect(() => {
    async function load() {
      try {
        const { listings: items } = await fetchUserListings()
        if (items?.length) {
          const mapped = items.map(item => ({
            id: item.id,
            title: item.title,
            category: item.category || 'General',
            conditionScore: item.condition_score || 80,
            conditionGrade: item.condition_grade || 'Good',
            price: Number(item.price) || 0,
            originalPrice: Number(item.original_price) || 0,
            image: item.image_url || null,
            additional_images: item.additional_images || [],
            tag: 'Just listed',
            rating: '—',
            reviews: 'New',
            delivery: 'FREE delivery by Amazon',
            conditionReport: {
              confidence: item.condition_score || 80,
              observations: item.observations || [],
              summary: item.condition_summary || item.description || '',
            },
            user_id: item.user_id ?? null,
            userListed: true,
            // Demo is a single fixed campus, so every freshly-resold item is local.
            // This is what makes a just-listed item appear in Campus automatically —
            // no matching step, purely a location match.
            location: DEMO_LOCATION,
            localHandoff: true,
          }))
          setUserItems(mapped)
        }
      } catch { /* silent fail */ }
    }
    load()
    const interval = setInterval(load, 5000)
    return () => clearInterval(interval)
  }, [])

  // For the demo there is one campus (IIT Patna) and every Encore item is available
  // there — Amazon returns, personal daily items, freshly-resold listings, anything.
  // So all inventory is treated as locally available for hand-to-hand campus pickup.
  const seedListings = listings.map(l => ({
    ...l,
    location: l.location ?? DEMO_LOCATION,
    localHandoff: l.localHandoff ?? true,
  }))
  const allListings = [...userItems, ...seedListings]

  // "My listings" tab: items the current user submitted (have user_id matching)
  const myListings = user
    ? allListings.filter(l => l.user_id === user.id || l.userListed)
    : []

  // "Campus" tab: listings at the user's location — passive location filter, no matching.
  const campusListings = allListings.filter(l => l.localHandoff || l.location === DEMO_LOCATION)

  const tabListings = activeTab === 'mine'
    ? myListings
    : activeTab === 'campus'
      ? campusListings
      : allListings
  const allCategories = [...new Set(tabListings.map(l => l.category).filter(Boolean))].sort()

  const q = searchQuery.trim().toLowerCase()
  const searchFiltered = q
    ? tabListings.filter(l =>
        l.title.toLowerCase().includes(q) ||
        l.category.toLowerCase().includes(q) ||
        l.conditionGrade.toLowerCase().includes(q) ||
        (l.conditionReport?.summary || '').toLowerCase().includes(q)
      )
    : tabListings

  const categoryFiltered = activeCategory
    ? searchFiltered.filter(l => l.category === activeCategory)
    : searchFiltered

  const counts = conditionCounts(categoryFiltered)
  const filtered = activeGrade
    ? categoryFiltered.filter(l => l.conditionGrade === activeGrade)
    : categoryFiltered

  function toggleReport(id) {
    setOpenReportId((prev) => (prev === id ? null : id))
  }

  return (
    <section id="marketplace" className="px-4 pb-10">
      <div className="max-w-[1500px] mx-auto">
        <div className="rounded-md border bg-white overflow-hidden" style={{ borderColor: '#D5D9D9' }}>
          <div className="grid xl:grid-cols-[250px_minmax(0,1fr)]">
            {/* Sidebar */}
            <aside
              className="border-b xl:border-b-0 xl:border-r bg-[#FBFBFB] p-5"
              style={{ borderColor: '#D5D9D9' }}
            >
              <h2 className="text-2xl font-bold mb-2" style={{ color: '#0F1111' }}>
                Encore marketplace
              </h2>
              <p className="text-sm text-[#565959] mb-5">
                AI-verified listings that look and shop like familiar Amazon results.
              </p>

              <div className="space-y-5 text-sm">
                <div>
                  <p className="font-bold text-[#0F1111] mb-2">Encore Verified</p>
                  <label className="flex items-center gap-2 text-[#565959] cursor-pointer">
                    <span
                      className="h-4 w-4 rounded-sm border flex items-center justify-center"
                      style={{ borderColor: '#D5D9D9', backgroundColor: '#067D62' }}
                    >
                      <ShieldCheck size={10} color="white" />
                    </span>
                    Show verified items only
                  </label>
                </div>

                <div>
                  <div className="flex items-center justify-between mb-2">
                    <p className="font-bold text-[#0F1111]">Condition</p>
                    {activeGrade && (
                      <button
                        type="button"
                        className="text-xs font-semibold"
                        style={{ color: '#007185' }}
                        onClick={() => setActiveGrade(null)}
                      >
                        Clear
                      </button>
                    )}
                  </div>
                  {CONDITION_ORDER.map((grade) => {
                    const count = counts[grade] ?? 0
                    if (!count) return null
                    const active = activeGrade === grade
                    return (
                      <button
                        key={grade}
                        type="button"
                        onClick={() => setActiveGrade(active ? null : grade)}
                        className="w-full flex items-center justify-between text-left mb-1 px-2 py-1 rounded transition-colors"
                        style={{
                          backgroundColor: active ? '#fff8e0' : 'transparent',
                          color: active ? '#c45500' : '#565959',
                        }}
                      >
                        <span className={active ? 'font-semibold' : ''}>{grade}</span>
                        <span className="text-xs">{count}</span>
                      </button>
                    )
                  })}
                </div>

                <div>
                  <p className="font-bold text-[#0F1111] mb-2">Second-life route</p>
                  {['Resell', 'Refurbished', 'Open-box'].map((item) => (
                    <div key={item} className="text-[#565959] mb-1 px-2">{item}</div>
                  ))}
                </div>
              </div>
            </aside>

            {/* Listings */}
            <div className="p-5 md:p-6">
              {/* Campus / All / My listings tab strip */}
              <div className="flex gap-2 mb-5 flex-wrap">
                {[
                  ['campus', `Campus — ${DEMO_LOCATION}`, MapPin, null],
                  ['all', 'All listings', null, null],
                  ...(user ? [['mine', 'My listings', Package, myListings.length]] : []),
                ].map(([key, label, Icon, count]) => (
                  <button
                    key={key}
                    type="button"
                    onClick={() => { setActiveTab(key); setActiveGrade(null); setActiveCategory(null) }}
                    className="flex items-center gap-1.5 px-4 py-2 rounded-full text-sm font-semibold border transition-colors"
                    style={{
                      backgroundColor: activeTab === key ? '#131921' : 'white',
                      color: activeTab === key ? 'white' : '#565959',
                      borderColor: activeTab === key ? '#131921' : '#D5D9D9',
                    }}
                  >
                    {Icon && <Icon size={13} />}
                    {label}
                    {count > 0 && (
                      <span
                        className="ml-1 px-1.5 py-0.5 rounded-full text-[10px] font-bold"
                        style={{ backgroundColor: '#FF9900', color: '#0F1111' }}
                      >
                        {count}
                      </span>
                    )}
                  </button>
                ))}
              </div>

              {/* Campus banner — shown only on the Campus / Near you tab */}
              {activeTab === 'campus' && (
                <div
                  className="rounded-md border p-5 mb-5"
                  style={{ borderColor: '#067D62', backgroundColor: '#f0faf5' }}
                >
                  <div className="flex items-center gap-2 mb-1">
                    <MapPin size={18} style={{ color: '#067D62' }} />
                    <h3 className="text-lg font-bold" style={{ color: '#0F1111' }}>
                      Encore Campus — {DEMO_LOCATION}
                    </h3>
                  </div>
                  <p className="text-sm text-[#565959] mb-2">
                    Everything available near you — Amazon returns, open-box deals, and items listed by
                    people on your campus. Picked up hand-to-hand, with zero return miles.
                  </p>
                  <p className="text-sm text-[#565959]">
                    <span className="font-semibold" style={{ color: '#067D62' }}>The idea:</span> when an
                    Amazon order is returned but costs too much to ship back to the warehouse and relist,
                    Encore lists it here at a discount — so someone nearby gets it cheap and it never
                    leaves the campus.
                  </p>
                </div>
              )}

              {/* Category chips — personalized if localStorage has a prior category */}
              {allCategories.length > 0 && (
                <div className="mb-5">
                  {savedCategory && !activeCategory && (
                    <p className="text-xs mb-2 text-[#565959]">
                      <span className="font-semibold" style={{ color: '#007185' }}>Recommended for you</span>
                      {' '}— based on your interest in {savedCategory}
                    </p>
                  )}
                  <div className="flex gap-2 flex-wrap">
                    <button
                      type="button"
                      onClick={() => setActiveCategory(null)}
                      className="px-3 py-1.5 rounded-full text-xs font-semibold border transition-colors"
                      style={{
                        borderColor: !activeCategory ? '#FF9900' : '#D5D9D9',
                        backgroundColor: !activeCategory ? '#fff8e0' : 'white',
                        color: !activeCategory ? '#c45500' : '#565959',
                      }}
                    >
                      All
                    </button>
                    {allCategories.map(cat => {
                      const isActive = activeCategory === cat
                      const isSaved = savedCategory === cat && !activeCategory
                      return (
                        <button
                          key={cat}
                          type="button"
                          onClick={() => {
                            const next = isActive ? null : cat
                            setActiveCategory(next)
                            if (next) {
                              localStorage.setItem('encore_last_category', next)
                              setSavedCategory(next)
                            }
                          }}
                          className="px-3 py-1.5 rounded-full text-xs font-semibold border transition-colors"
                          style={{
                            borderColor: isActive ? '#FF9900' : isSaved ? '#007185' : '#D5D9D9',
                            backgroundColor: isActive ? '#fff8e0' : isSaved ? '#e0f0f3' : 'white',
                            color: isActive ? '#c45500' : isSaved ? '#007185' : '#565959',
                          }}
                        >
                          {cat}{isSaved ? ' ★' : ''}
                        </button>
                      )
                    })}
                  </div>
                </div>
              )}

              <div className="flex flex-col md:flex-row md:items-end md:justify-between gap-3 mb-6">
                <div>
                  <p className="text-sm text-[#565959]">
                    1–{filtered.length} of {filtered.length} result{filtered.length !== 1 ? 's' : ''}
                    {q ? ` for "${searchQuery}"` : activeGrade ? ` for "${activeGrade}"` : ' for Encore picks'}
                  </p>
                  <h3 className="text-2xl font-bold text-[#0F1111]">
                    {q ? `Results for "${searchQuery}"` : activeGrade ? `${activeGrade} condition` : activeTab === 'campus' ? `Near you · ${DEMO_LOCATION}` : 'Popular second-life listings'}
                  </h3>
                </div>
                <p className="text-sm font-semibold" style={{ color: '#007185' }}>
                  Prices reflect condition, not wishful thinking
                </p>
              </div>

              {/* Second-life books featured section — hidden when searching non-book term */}
              {(() => {
                const bookListings = listings.filter((l) => l.category === 'Books')
                if (!bookListings.length) return null
                if (q && !q.includes('book')) return null
                if (activeTab !== 'all') return null

                function extractAttr(observations, keywords) {
                  const obs = observations.find((o) =>
                    keywords.some((k) => o.toLowerCase().includes(k))
                  )
                  if (!obs) return null
                  const negatives = ['tear', 'crack', 'damage', 'worn', 'bend', 'bent', 'dog-ear', 'pen ']
                  const isNeg = negatives.some((n) => obs.toLowerCase().includes(n))
                  return { text: obs, positive: !isNeg }
                }

                return (
                  <div
                    className="rounded-md border p-5 mb-6"
                    style={{ borderColor: '#D5D9D9', backgroundColor: '#f0faf5' }}
                  >
                    <div className="flex items-center gap-2.5 mb-1">
                      <BookOpen size={20} style={{ color: '#067D62' }} />
                      <h4 className="text-lg font-bold" style={{ color: '#0F1111' }}>
                        Second-life books
                      </h4>
                    </div>
                    <p className="text-sm text-[#565959] mb-4">
                      Where it all started. Amazon began selling books — Encore brings them back.
                    </p>

                    <div className="overflow-x-auto">
                      <div className="flex gap-4">
                        {bookListings.map((book) => {
                          const cfg = CONDITION_COLOR[book.conditionGrade] ?? CONDITION_COLOR['Good']
                          const fallback = `https://picsum.photos/seed/${book.id}/400/400`
                          const spine = extractAttr(book.conditionReport.observations, ['spine'])
                          const annotations = extractAttr(book.conditionReport.observations, ['annotation', 'highlight', 'pencil', 'note', 'pen'])
                          const pages = extractAttr(book.conditionReport.observations, ['page', 'intact'])

                          return (
                            <div
                              key={book.id}
                              className="min-w-[280px] max-w-[300px] rounded-md border bg-white p-4 flex flex-col gap-3 flex-shrink-0 cursor-pointer hover:shadow-md transition-shadow"
                              style={{ borderColor: '#D5D9D9' }}
                              onClick={() => onProductClick?.(book)}
                            >
                              <div className="h-[140px] rounded-md overflow-hidden border" style={{ borderColor: '#D5D9D9' }}>
                                <img
                                  src={book.image ?? fallback}
                                  alt={book.title}
                                  onError={(e) => { e.target.src = fallback }}
                                  className="w-full h-full object-cover"
                                />
                              </div>

                              <button
                                type="button"
                                onClick={() => onProductClick?.(book)}
                                className="text-left text-sm font-medium leading-snug hover:underline line-clamp-2"
                                style={{ color: '#007185' }}
                              >
                                {book.title}
                              </button>

                              <div className="flex items-center gap-2">
                                <span
                                  className="inline-flex rounded-full px-2.5 py-0.5 text-[10px] font-bold uppercase tracking-wide"
                                  style={{ backgroundColor: cfg.bg, color: cfg.color }}
                                >
                                  {book.conditionGrade}
                                </span>
                                <span className="text-xs text-[#565959]">Score: {book.conditionScore}/100</span>
                              </div>

                              <div className="flex items-baseline gap-2">
                                <span className="text-xl font-medium" style={{ color: '#0F1111' }}>
                                  ₹{book.price.toLocaleString('en-IN')}
                                </span>
                                <span className="text-sm text-[#565959] line-through">
                                  ₹{book.originalPrice.toLocaleString('en-IN')}
                                </span>
                              </div>

                              <div className="border-t pt-3" style={{ borderColor: '#D5D9D9' }}>
                                <p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#879596] mb-2">
                                  Book condition
                                </p>
                                <div className="space-y-1.5">
                                  {spine && (
                                    <div className="flex items-center gap-1.5 text-xs">
                                      {spine.positive
                                        ? <CheckCircle2 size={13} style={{ color: '#067D62' }} />
                                        : <AlertTriangle size={13} style={{ color: '#c45500' }} />}
                                      <span className="text-[#565959]"><span className="font-semibold text-[#0F1111]">Spine:</span> {spine.text}</span>
                                    </div>
                                  )}
                                  {annotations && (
                                    <div className="flex items-center gap-1.5 text-xs">
                                      {annotations.positive
                                        ? <CheckCircle2 size={13} style={{ color: '#067D62' }} />
                                        : <AlertTriangle size={13} style={{ color: '#c45500' }} />}
                                      <span className="text-[#565959]"><span className="font-semibold text-[#0F1111]">Annotations:</span> {annotations.text}</span>
                                    </div>
                                  )}
                                  {pages && (
                                    <div className="flex items-center gap-1.5 text-xs">
                                      {pages.positive
                                        ? <CheckCircle2 size={13} style={{ color: '#067D62' }} />
                                        : <AlertTriangle size={13} style={{ color: '#c45500' }} />}
                                      <span className="text-[#565959]"><span className="font-semibold text-[#0F1111]">Pages:</span> {pages.text}</span>
                                    </div>
                                  )}
                                </div>
                              </div>
                            </div>
                          )
                        })}
                      </div>
                    </div>
                  </div>
                )
              })()}

              {activeTab === 'mine' && myListings.length === 0 && (
                <div className="py-16 text-center">
                  <Package size={40} className="mx-auto mb-4" style={{ color: '#D5D9D9' }} />
                  <p className="text-lg font-semibold text-[#0F1111] mb-1">No listings yet</p>
                  <p className="text-sm text-[#565959]">Items you list through Encore will appear here.</p>
                </div>
              )}

              <div className="divide-y" style={{ borderColor: '#E7E7E7' }}>
                {filtered.map((product) => {
                  const cfg = CONDITION_COLOR[product.conditionGrade] ?? CONDITION_COLOR['Good']
                  const isOpen = openReportId === product.id
                  return (
                    <div key={product.id} className="py-5 first:pt-0 last:pb-0"
                      style={product.userListed ? { borderLeft: '3px solid #FF9900', paddingLeft: 16, backgroundColor: '#fffdf5' } : {}}>
                      <div className="flex flex-col md:flex-row gap-5">
                        <div className="cursor-pointer" onClick={() => onProductClick?.(product)}>
                          <ProductImage product={product} />
                        </div>

                        <div className="min-w-0 flex-1">
                          <div className="flex items-center gap-2 mb-2 flex-wrap">
                            <ShieldCheck size={14} style={{ color: '#067D62' }} />
                            <span className="text-xs font-bold uppercase tracking-wide text-[#067D62]">
                              Encore Verified
                            </span>
                            {product.userListed && (
                              <span className="text-[10px] font-bold uppercase tracking-wider px-2.5 py-0.5 rounded-full"
                                style={{ backgroundColor: '#FF9900', color: '#fff' }}>
                                Just listed
                              </span>
                            )}
                            {product.localHandoff && (
                              <span className="inline-flex items-center gap-1 text-[10px] font-bold uppercase tracking-wider px-2.5 py-0.5 rounded-full"
                                style={{ backgroundColor: '#e6f4ea', color: '#067D62' }}>
                                <MapPin size={10} />
                                Local handoff
                              </span>
                            )}
                            <span className="text-xs text-[#565959]">{product.category}</span>
                          </div>

                          <button
                            type="button"
                            onClick={() => onProductClick?.(product)}
                            className="block text-left text-lg leading-snug font-medium hover:underline"
                            style={{ color: '#007185' }}
                          >
                            {product.title}
                          </button>

                          <div className="flex items-center gap-2 flex-wrap mt-1 text-sm">
                            <span className="text-[#C7511F]">★★★★☆</span>
                            <span style={{ color: '#007185' }}>{product.rating}</span>
                            <span style={{ color: '#007185' }}>({product.reviews})</span>
                            <span className="text-[#565959]">
                              Condition score: {product.conditionScore}/100
                            </span>
                          </div>

                          <div className="flex items-center gap-2 flex-wrap mt-2">
                            <span
                              className="inline-flex rounded-full px-3 py-1 text-xs font-bold"
                              style={{ backgroundColor: cfg.bg, color: cfg.color }}
                            >
                              {product.conditionGrade}
                            </span>
                            {product.conditionReport.summary ? (
                              <span className="text-sm text-[#565959]">
                                {product.conditionReport.summary.length > 80
                                  ? `${product.conditionReport.summary.slice(0, 80)}…`
                                  : product.conditionReport.summary}
                              </span>
                            ) : null}
                          </div>

                          {product.localHandoff ? (
                            <>
                              <p className="text-sm mt-3 inline-flex items-center gap-1 font-medium" style={{ color: '#067D62' }}>
                                <MapPin size={13} />
                                Campus handoff · {product.location || DEMO_LOCATION}
                              </p>
                              <p className="text-sm mt-1 font-medium" style={{ color: '#067D62' }}>
                                Hand-to-hand on campus · instant for the seller · zero return miles
                              </p>
                            </>
                          ) : (
                            <>
                              <p className="text-sm mt-3" style={{ color: '#067D62' }}>
                                {product.delivery}
                              </p>
                              <p className="text-sm text-[#565959] mt-1">
                                30-day return window. Backed by Encore condition support.
                              </p>
                            </>
                          )}
                        </div>

                        <div className="md:w-[210px] flex-shrink-0">
                          <div
                            className="rounded-md border p-4 bg-[#FBFBFB]"
                            style={{ borderColor: '#D5D9D9' }}
                          >
                            <p className="text-[13px] text-[#565959] mb-1">Starting price</p>
                            {product.price > 0 ? (
                              <>
                                <div className="flex items-baseline gap-2 flex-wrap">
                                  <span className="text-3xl font-medium text-[#0F1111]">
                                    ₹{product.price.toLocaleString('en-IN')}
                                  </span>
                                  {product.originalPrice > 0 && (
                                    <span className="text-sm text-[#565959] line-through">
                                      ₹{product.originalPrice.toLocaleString('en-IN')}
                                    </span>
                                  )}
                                </div>
                                {product.originalPrice > 0 && product.price < product.originalPrice && (
                                  <p className="text-sm font-semibold mt-1" style={{ color: '#067D62' }}>
                                    {Math.round((1 - product.price / product.originalPrice) * 100)}% off original
                                  </p>
                                )}
                              </>
                            ) : (
                              <p className="text-base font-semibold mt-1 text-[#565959]">Price on request</p>
                            )}
                            {product.price > 0 && (
                              <button
                                type="button"
                                onClick={() => handleAddToCart(product)}
                                className="mt-4 w-full py-2.5 rounded-full font-semibold text-sm transition-all flex items-center justify-center gap-2"
                                style={{
                                  backgroundColor: addedId === product.id ? '#067D62' : '#FFD814',
                                  color: addedId === product.id ? 'white' : '#0F1111',
                                }}
                              >
                                <ShoppingCart size={14} />
                                {addedId === product.id ? 'Added to cart' : 'Add to cart'}
                              </button>
                            )}
                            {product.price > 0 && (
                              <button
                                type="button"
                                onClick={() => handleBuyNow(product)}
                                className="mt-2 w-full py-2.5 rounded-full font-semibold text-sm transition-all flex items-center justify-center gap-2"
                                style={{ backgroundColor: '#FF9900', color: 'white' }}
                              >
                                <Zap size={14} />
                                Buy now
                              </button>
                            )}
                            <button
                              type="button"
                              onClick={() => toggleReport(product.id)}
                              className="mt-2 w-full py-2 rounded-full border text-sm font-semibold flex items-center justify-center gap-1.5 transition-all"
                              style={{
                                borderColor: isOpen ? '#007185' : '#D5D9D9',
                                color: isOpen ? '#007185' : '#0F1111',
                                backgroundColor: isOpen ? '#e0f0f3' : '#F7F8F8',
                              }}
                            >
                              {isOpen ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
                              {isOpen ? 'Hide report' : 'See condition report'}
                            </button>
                          </div>
                        </div>
                      </div>

                      {isOpen && (
                        <ConditionReport item={product} onClose={() => setOpenReportId(null)} />
                      )}
                    </div>
                  )
                })}
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
